preset: laravel

risky: true

enabled:
  - declare_strict_types
  - dir_constant
  - is_null
  - linebreak_after_opening_tag
  - logical_operators
  - mb_str_functions
  - native_constant_invocation
  - native_function_invocation
  - no_php4_constructor
  - no_superfluous_phpdoc_tags
  - not_operator_with_space
  - phpdoc_order
  - phpdoc_separation
  - pow_to_exponentiation
  - random_api_migration
  - single_trait_insert_per_statement
  - ternary_to_null_coalescing
  - unalign_double_arrow

disabled:
  - phpdoc_var_without_name

finder:
  exclude:
    - "node_modules"
    - "tests"
    - "vendor"
  name:
    - "*.php"
